//
//  StorePresenter.swift
//  Teremok-TV
//
//  Created by R9G on 04/12/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StorePresentationLogic: CommonPresentationLogic {
    func presentPurchase()
    func presentProduct(_ price: String)
    func successPurchase()
}

class StorePresenter: StorePresentationLogic {
    weak var viewController: StoreDisplayLogic?
    
    var displayModule: CommonDisplayLogic? {
        return viewController
    }
    // MARK: Do something
    func presentPurchase(){
        viewController?.displayPurchase()
    }

    func successPurchase() {
        viewController?.successPurchase()
    }
    
    func presentProduct(_ price: String){
        
    }
}
