//
//  StoreModels.swift
//  Teremok-TV
//
//  Created by R9G on 04/12/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Store {
    // MARK: Use cases
  
//    enum Subscriptions {
//        case music
//        case video
//    }
}
