//
//  ChildsInteractor.swift
//  Teremok-TV
//
//  Created by R9G on 13/10/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildsBusinessLogic {
    func switchChild(id: String)
}

protocol ChildsDataStore {
    
}

class ChildsInteractor: ChildsBusinessLogic, ChildsDataStore {
    var presenter: ChildsPresentationLogic?
    let service: ProfileProtocol = ProfileService()
    

    // MARK: Do something

    func switchChild(id: String){
        service.switchChild(with: id){  [weak self] (response) in
        switch response {
        case .success(let result):
            self?.presenter?.presentProfile(model: result)
        case .failure(let error):
            self?.presenter?.presentError(error: error, completion: nil)
        }
    }
    }
    
}
