//
//  ChildsRouter.swift
//  Teremok-TV
//
//  Created by R9G on 13/10/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildsRoutingLogic: CommonRoutingLogic {
    func navigateToChild(_ model: GetProfileResponse)
    func navigateAddChild()
}

protocol ChildsDataPassing {
    var dataStore: ChildsDataStore? { get }
}

class ChildsRouter: NSObject, ChildsRoutingLogic, ChildsDataPassing {
    weak var viewController: ChildsViewController?
    var dataStore: ChildsDataStore?
    var modalControllersQueue = Queue<UIViewController>()

    // MARK: Routing
    func navigateToChild(_ model: GetProfileResponse){
        let profile = ChildProfileViewController.instantiate(fromStoryboard: .profile)
        guard var dataStore = profile.router?.dataStore else { return }
        dataStore.profileModel = model
        viewController?.masterRouter?.pushChild(profile)
    }
    func navigateAddChild(){
        let vc = ChildProfileAddViewController.instantiate(fromStoryboard: .autorization)
        guard var dataStore = vc.router?.dataStore else { return }
        dataStore.screen = .Add
        viewController?.masterRouter?.pushChild(vc)
    }
}
