//
//  ChildsPresenter.swift
//  Teremok-TV
//
//  Created by R9G on 13/10/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildsPresentationLogic: CommonPresentationLogic {
    func presentProfileData()
    func presentProfile(model: GetProfileResponse)
}

class ChildsPresenter: ChildsPresentationLogic {
    weak var viewController: ChildsDisplayLogic?
    
    var displayModule: CommonDisplayLogic? {
        return viewController
    }
    // MARK: Do something
    func presentProfileData() {
        viewController?.displayProfile()
    }
    func presentProfile(model: GetProfileResponse){
        viewController?.displayChildProfile(model: model)
    }
}
