//
//  ChildProfileDoneRouter.swift
//  Teremok-TV
//
//  Created by R9G on 14/09/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildProfileDoneRoutingLogic: CommonRoutingLogic {
    func routToMain()
    func navigateToAddChild()
}

protocol ChildProfileDoneDataPassing {
    var dataStore: ChildProfileDoneDataStore? { get }
}

class ChildProfileDoneRouter: NSObject, ChildProfileDoneRoutingLogic, ChildProfileDoneDataPassing {
    weak var viewController: ChildProfileDoneViewController?
    var dataStore: ChildProfileDoneDataStore?
    var modalControllersQueue = Queue<UIViewController>()

    // MARK: Routing

    func routToMain(){
        viewController?.masterRouter?.pushChild(viewControllerClass: MainViewController.self, storyboard: .main)
        
    }
    func navigateToAddChild(){
        let vc = ChildProfileAddViewController.instantiate(fromStoryboard: .autorization)
        guard var dataStore = vc.router?.dataStore else { return }
        dataStore.screen = .Add
        viewController?.masterRouter?.pushChild(vc)
    }
}
