//
//  ChildProfileDoneInteractor.swift
//  Teremok-TV
//
//  Created by R9G on 14/09/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildProfileDoneBusinessLogic {
    func fectchData()
}

protocol ChildProfileDoneDataStore {

    var screen: ChildProfileAdd.Screen? {get set}
    var child: Child? {get set}

}

class ChildProfileDoneInteractor: ChildProfileDoneBusinessLogic, ChildProfileDoneDataStore {
    
    var child: Child?
    
    var screen: ChildProfileAdd.Screen?

    var presenter: ChildProfileDonePresentationLogic?

    var profileService: ProfileProtocol = ProfileService()
    
    func fectchData(){
        if let screen = self.screen {
            switch screen {
            case .Modify(_ ), .Add:
                NotificationCenter.default.post(name: NSNotification.Name.ProfileNeedReload, object: nil)
            default:
                break
            }
            
        }
        guard let child = self.child else {
            return
        }
        self.presenter?.presentData(child: child, title: screen?.doneTitle ?? "")
    }

    
    // MARK: Do something

}
