//
//  ChildProfileDoneViewController.swift
//  Teremok-TV
//
//  Created by R9G on 14/09/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildProfileDoneDisplayLogic: CommonDisplayLogic {
    func displayData(name: String, ageAndSex: String, title: String, pic: String?)
}

class ChildProfileDoneViewController: AbstracViewController, ChildProfileDoneDisplayLogic {
    var activityView: LottieHUD?
    
    var interactor: ChildProfileDoneBusinessLogic?
    var router: (NSObjectProtocol & ChildProfileDoneRoutingLogic & ChildProfileDoneDataPassing & CommonRoutingLogic)?
    var modallyControllerRoutingLogic: CommonRoutingLogic? {
        get { return router }
    }
    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = ChildProfileDoneInteractor()
        let presenter = ChildProfileDonePresenter()
        let router = ChildProfileDoneRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    @IBOutlet private var nameLbl: UILabel!
    @IBOutlet private var ageAndSexLbl: UILabel!
    @IBOutlet private var titleLbl: UILabel!
    @IBOutlet private var addChildBtn: UIButton!
    
    @IBAction func addChildClick(_ sender: Any) {
        router?.navigateToAddChild()
    }
    
    @IBOutlet private var avatarBtn: AvatarButton!
    @IBAction func doneClick(_ sender: Any) {
        self.router?.routToMain()
    }
    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.interactor?.fectchData()
    }
    
    // MARK: Do something

    func displayData(name: String, ageAndSex: String, title: String, pic: String?) {
        titleLbl.text = title
        nameLbl.text = name
        ageAndSexLbl.text = ageAndSex
        if let link = pic {
            avatarBtn.setAvatar(linktoLoad: link)
        }
    }
}
