//
//  MainPresenter.swift
//  Teremok-TV
//
//  Created by R9G on 22.08.2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic: CommonPresentationLogic {
    func presentMainRazdels(_ models: [RazdelModel])
    func presentSeriesRazdel(razdelId: Int, items: [RazdelItemResponse])
}

class MainPresenter: MainPresentationLogic {
    var displayModule: CommonDisplayLogic? {
        return viewController
    }
    weak var viewController: MainDisplayLogic?
  
    
    // MARK: Do something
    
    func presentMainRazdels(_ models: [RazdelModel]) {
        
        let items = models.map { Main.RazdelItem(title: $0.name ?? "", link: $0.animationUrl ?? "") }
        viewController?.display(razdels: items)
    }
    
    func presentSeriesRazdel(razdelId: Int, items: [RazdelItemResponse]){
        
        var serials: [RazdelVCModel.SerialItem] = []
        for item in items {
            let serial = RazdelVCModel.SerialItem(name: item.name ?? "", imageUrl: item.poster ?? "", description: item.description ?? "")
            serials.append(serial)
        }
        
        viewController?.seriesDisplay(razdelId: razdelId, show: serials)
    }
}
