//
//  PuzzleMasterModels.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 22.03.2020.
//  Copyright (c) 2020 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PuzzleMaster {

	static let funSounds = ["fun_4", "fun_5", "fun_6", "fun_7"]

	static let firstPack: [String] = [
		"puzzle_1",
		"puzzle_2",
		"puzzle_3",
		"puzzle_4",
		"puzzle_5",
		"puzzle_6",
		"puzzle_7",
		"puzzle_8",
		"puzzle_9",
		"puzzle_10",
		"puzzle_11",
		"puzzle_12",
		"puzzle_13",
		"puzzle_14",
		"puzzle_15",
	]

	static let secondPack: [String] = [
		"puzzle_16",
		"puzzle_17",
		"puzzle_18",
		"puzzle_19",
		"puzzle_20",
		"puzzle_21",
		"puzzle_22",
		"puzzle_23",
		"puzzle_24",
		"puzzle_25",
		"puzzle_26",
		"puzzle_27",
		"puzzle_28",
		"puzzle_29",
		"puzzle_30",
	]

	static let thirdPack: [String] = [
		"puzzle_30",
		"puzzle_31",
		"puzzle_32",
		"puzzle_33",
		"puzzle_34",
		"puzzle_35",
		"puzzle_36",
		"puzzle_37",
		"puzzle_38",
		"puzzle_39",
		"puzzle_40",
		"puzzle_41",
		"puzzle_42",
		"puzzle_43",
		"puzzle_44",
		"puzzle_45",
		"puzzle_46",
		"puzzle_47",
		"puzzle_48",
		"puzzle_49",
		"puzzle_50",
	]
}
