//
//  PuzzleMasterInteractor.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 22.03.2020.
//  Copyright (c) 2020 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PuzzleMasterBusinessLogic {
    
}

protocol PuzzleMasterDataStore {
    
}

class PuzzleMasterInteractor: PuzzleMasterBusinessLogic, PuzzleMasterDataStore {
    var presenter: PuzzleMasterPresentationLogic?    

    // MARK: Do something

}
