excluded:
  - Pods
  - variable_name

disabled_rules:
  - trailing_whitespace
  - unused_optional_binding
  - nesting
  - type_name

line_length:
  warning: 160
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 40
  error: 60
