//
//  FavRouter.swift
//  Teremok-TV
//
//  Created by R9G on 14/09/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavRoutingLogic: CommonRoutingLogic {
    func navigateToFavPreview(number: Int)
    func navigateToSavedPreview(number: Int)
}

protocol FavDataPassing {
    var dataStore: FavDataStore? { get }
}

class FavRouter: NSObject, FavRoutingLogic, FavDataPassing {
    weak var viewController: FavViewController?
    var dataStore: FavDataStore?
    var modalControllersQueue = Queue<UIViewController>()

    // MARK: Routing
    
    func navigateToFavPreview(number: Int){
        let serials = PreviewViewController.instantiate(fromStoryboard: .play)
        guard var dataStore = serials.router?.dataStore else { return }
        guard let id = viewController?.router?.dataStore?.videoModels[safe: number]?.id else {
            return
        }
        dataStore.model = .online(id: id)
        dataStore.razdId = 0
        viewController?.masterRouter?.presentNextChild(viewController: serials)
    }

    func navigateToSavedPreview(number: Int){
        let serials = PreviewViewController.instantiate(fromStoryboard: .play)
        guard var dataStore = serials.router?.dataStore else { return }
        guard let videoModels = self.dataStore?.offlineVideos, videoModels[safe: number] != nil else {
            return
        }
        dataStore.model = .offline(idx: number, models: videoModels)
        viewController?.masterRouter?.presentNextChild(viewController: serials)
    }
}
