//
//  AlphaviteMasterPresenter.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 01/08/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlphaviteMasterPresentationLogic: CommonPresentationLogic {
}

class AlphaviteMasterPresenter: AlphaviteMasterPresentationLogic {
    var displayModule: CommonDisplayLogic? {
        return viewController
    }
    weak var viewController: AlphaviteMasterDisplayLogic?

}
