//
//  AlphaviteMasterViewController.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 01/08/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AVKit
import Trackable

protocol AlphaviteMasterDisplayLogic: MasterModuleDisplayLogic, TrackableClass {
    
}

class AlphaviteMasterViewController: GameMasterViewController, AlphaviteMasterDisplayLogic {
    var interactor: AlphaviteMasterBusinessLogic?
    var router: (CommonRoutingLogic & AlphaviteMasterRoutingLogic & AlphaviteMasterDataPassing)?
    var modallyControllerRoutingLogic: CommonRoutingLogic? {
        get { return router }
    }
    var activityView: LottieHUD?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = AlphaviteMasterInteractor()
        let presenter = AlphaviteMasterPresenter()
        let router = AlphaviteMasterRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: View lifecycle

    @IBAction func avatarClick(_ sender: Any) {
        tipView?.dismiss()
        router?.openStatistic()
    }

    @IBAction private func homeClick(_ sender: Any) {
        if router?.canPop() ?? false {
            router?.popChild()
        } else {
            dismiss(animated: true, completion: nil)
        }
    }
    let bundleResourceRequest = NSBundleResourceRequest(tags: Set([OnDemandLoader.Tags.Prefetch.alphabetImages.rawValue, OnDemandLoader.Tags.Prefetch.alphabetSounds.rawValue]))

    override func viewDidLoad() {
        super.viewDidLoad()

        bundleResourceRequest.conditionallyBeginAccessingResources { [unowned self] available in
            DispatchQueue.main.async {
                if available {
                      self.router?.navigateMain()
                  } else {
                    self.bundleResourceRequest.beginAccessingResources { error in
                          guard error == nil else { return }

                          self.present(errorString: "Игра загружается, попробуйте позже") {
                              self.dismiss(animated: true)
                          }
                      }
                  }
            }

        }
        do {
            //Preparation to play
            try AVAudioSession.sharedInstance().setCategory(AVAudioSession.Category.playback, mode: .moviePlayback)
            try AVAudioSession.sharedInstance().setActive(true, options: .notifyOthersOnDeactivation)
        }
        catch {
            // report for an error
        }
        displayProfile()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)

        if !avatarButton.isHidden, LocalStore.alphabetTip < 3 {
            LocalStore.alphabetTip += 1
            var preferences = EasyTipView.Preferences()
            preferences.drawing.font = Style.Font.istokWeb(size: 16)
            preferences.drawing.foregroundColor = UIColor.View.titleText
            preferences.drawing.backgroundColor = .white
            preferences.drawing.arrowPosition = EasyTipView.ArrowPosition.right
            tipView = EasyTipView(text: "Здесь можно посмотреть статистику", preferences: preferences, delegate: self)
            tipView?.show(animated: true, forView: avatarButton, withinSuperview: view)
        }
    }

    // MARK: Do something


    deinit {
        track(
            Events.Time.AlphabetFlow,
            trackedProperties: [Keys.Timer  ~>> NSDate().timeIntervalSince(startTime)]
        )
        if ServiceConfiguration.activeConfiguration().logging {
            print("Logger: deinit \(className)")
        }
        do {
            //Preparation to play - Костыль
            try AVAudioSession.sharedInstance().setCategory(AVAudioSession.Category.ambient, mode: .moviePlayback)
            try AVAudioSession.sharedInstance().setActive(true, options: .notifyOthersOnDeactivation)
        }
        catch {
            // report for an error
        }
    }
}

extension AlphaviteMasterViewController: EasyTipViewDelegate {
    func easyTipViewDidDismiss(_ tipView: EasyTipView) {
        tipView.dismiss()
    }
}
