//
//  AlbumPresenter.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 17/03/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlbumPresentationLogic: CommonPresentationLogic {
    func present(items: [MusicAlbumResponse])

}

class AlbumPresenter: AlbumPresentationLogic {
    weak var viewController: AlbumDisplayLogic?
  
    var displayModule: CommonDisplayLogic? {
        return viewController
    }

    func present(items: [MusicAlbumResponse]){

        var albums: [Album.Item] = []
        for item in items {
            let album = Album.Item(name: item.name ?? "", imageUrl: item.poster ?? "", description: item.description ?? "")
            albums.append(album)
        }
        viewController?.displayAlbums(albums)
    }
}
