//
//  MasterModels.swift
//  Teremok-TV
//
//  Created by R9G on 16/09/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum GameFlow {
    case Animals
    case Alphabet
    case Colors
    case Monsters
}
