//
//  MasterPresenter.swift
//  Teremok-TV
//
//  Created by R9G on 16/09/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MasterPresentationLogic: CommonPresentationLogic {
    func presentAuthScreen()
    func presentProfileData()
    func presentMain()
}

final class MasterPresenter: MasterPresentationLogic {
    weak var viewController: MasterDisplayLogic?
    
    var displayModule: CommonDisplayLogic? {
        return viewController
    }
    // MARK: Do something
    func presentAuthScreen(){
        viewController?.displayAuth()
    }
    
    func presentMain(){
        viewController?.showMain()
    }
    func presentProfileData() {
        viewController?.displayProfile()
    }
    
}
