//
//  ColorsMasterModels.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 08/09/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ColorsMaster {

    enum Colors: String {
        case white = "Белый"
        case black = "Черный"

        case red = "Красный"
        case orange = "Оранжевый"
        case yellow = "Желтый"
        case green = "Зеленый"
        case lightBlue = "Голубой"
        case blue = "Синий"
        case violet = "Фиолетовый"

        var sound: String {
            switch self {
                case .white:
                    return ""
                case .black:
                    return ""
                case .red:
                    return ""
                case .orange:
                    return ""
                case .yellow:
                    return ""
                case .green:
                    return ""
                case .lightBlue:
                    return ""
                case .blue:
                    return ""
                case .violet:
                    return ""
            }
        }
    }

    static let Pack: [Colors: UIImage?] = [
        Colors.white: ColorsMaster.images[0],
        Colors.black: ColorsMaster.images[1],
        Colors.red: ColorsMaster.images[2],
        Colors.orange: ColorsMaster.images[3],
        Colors.yellow: ColorsMaster.images[4],
        Colors.green: ColorsMaster.images[5],
        Colors.lightBlue: ColorsMaster.images[6],
        Colors.blue: ColorsMaster.images[7],
        Colors.violet: ColorsMaster.images[8]
    ]

    static let images: [UIImage?] = [
        UIImage(named: "animal_1"),
        UIImage(named: "animal_1"),
        UIImage(named: "animal_1"),
        UIImage(named: "animal_1"),
        UIImage(named: "animal_1"),
        UIImage(named: "animal_1"),
        UIImage(named: "animal_1"),
        UIImage(named: "animal_1"),
        UIImage(named: "animal_1")
    ]
}

extension ColorsMaster.Colors {
    var value: [UIColor] {
        get {
            switch self {
                case .yellow:
                    return [UIColor.ColorsGame.yellowOne, UIColor.ColorsGame.yellowTwo]
                case .orange:
                    return [UIColor.ColorsGame.orangeOne, UIColor.ColorsGame.orangeTwo]
                case .blue:
                    return [UIColor.ColorsGame.blueOne, UIColor.ColorsGame.blueTwo]
                case .red:
                    return [UIColor.ColorsGame.redOne, UIColor.ColorsGame.redTwo]
                case .green:
                    return [UIColor.ColorsGame.greenOne, UIColor.ColorsGame.greenTwo]
                case .white:
                    return [.white, .white]
                case .black:
                    return [.black, .black]
                case .lightBlue:
                    return [UIColor.ColorsGame.lightBlueOne, UIColor.ColorsGame.lightBlueTwo]
                case .violet:
                    return [UIColor.ColorsGame.violetOne, UIColor.ColorsGame.violetTwo]
            }
        }
    }
}
