//
//  SearchPresenter.swift
//  Teremok-TV
//
//  Created by R9G on 12/10/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic: CommonPresentationLogic {
    
    func presentTags(items: [SearchItemResponse])
    func presentSerial(id: Int, title: String)
}

class SearchPresenter: SearchPresentationLogic {
    
    func presentTags(items: [SearchItemResponse]){
        var tags: [Search.Tag] = []
        
        for item in items  {
            //let serial = Search.Tag(title: item.name ?? "", subtitle: item.description ?? "", imageLink: item.picture ?? "")
            let tag = Search.Tag(imageLink: item.pictureUrl ?? "")
            tags.append(tag)
        }
        viewController?.displayTags(items: tags)
        
    }
    
    func presentSerial(id: Int, title: String) {
        
        viewController?.displaySerial(id: id, title: title)
    }
    
    weak var viewController: SearchDisplayLogic?
  
    var displayModule: CommonDisplayLogic? {
        return viewController
    }
    // MARK: Do something
    
}
