//
//  RazdelRouter.swift
//  Teremok-TV
//
//  Created by R9G on 02/09/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RazdelRoutingLogic: CommonRoutingLogic {
    func navigateToSerial(number: Int)
    func navigateDescription(item: RazdelVCModel.SerialItem?)
}

protocol RazdelDataPassing {
    var dataStore: RazdelDataStore? { get }
}

class RazdelRouter: NSObject, RazdelRoutingLogic, RazdelDataPassing {
    weak var viewController: RazdelViewController?
    var dataStore: RazdelDataStore?
    var modalControllersQueue = Queue<UIViewController>()


    func navigateToSerial(number: Int){
        let serials = SerialViewController.instantiate(fromStoryboard: .main)
        guard var dataStore = serials.router?.dataStore else { return }
        guard let razdel = viewController?.router?.dataStore?.items[safe: number] else { return }
        guard let id = razdel.id else { return }
        dataStore.screen = .razdel(id)
        dataStore.razdelTitle = razdel.name ?? ""
        viewController?.masterRouter?.presentNextChild(viewController: serials)
    }
    
    func navigateDescription(item: RazdelVCModel.SerialItem?){
        let vc = RazdelDescriptionViewController.instantiate(fromStoryboard: .alerts)
        vc.item = item
        vc.delegate = viewController
        vc.modalTransitionStyle = .crossDissolve
        viewController?.present(vc, animated: true, completion: nil)
    }
    
}
