//
//  ChildProfilePresenter.swift
//  Teremok-TV
//
//  Created by R9G on 12/10/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildProfilePresentationLogic: CommonPresentationLogic {
    func presentProfileData()
    func present(items: [VideoModel])
    func presentAchievment(_ ach: [AchievementsResponse])
}

class ChildProfilePresenter: ChildProfilePresentationLogic {
    weak var viewController: ChildProfileDisplayLogic?
  
    var displayModule: CommonDisplayLogic? {
        return viewController
    }
    // MARK: Do something
    func presentProfileData() {
        viewController?.displayProfile()
    }
    
    func present(items: [VideoModel]){
        var fav: [PreviewModel] = []
        
        for item in items  {
            let serial = PreviewModel(title: item.name ?? "", subtitle: item.description ?? "", imageLink: .url(URL(string: item.picture ?? "")))
            fav.append(serial)
        }
        viewController?.displayFavorites(items: fav)
    }
    
    func presentAchievment(_ ach: [AchievementsResponse]){
        let items = ach.filter({$0.state ?? false})
        viewController?.displayAchieves(items.count.stringValue)
    }
}
