//
//  MonsterMasterPresenter.swift
//  Teremok-TV
//
//  Created by Дмитрий Грищенко on 15/08/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MonsterMasterPresentationLogic {
    
}

class MonsterMasterPresenter: MonsterMasterPresentationLogic {
    weak var viewController: MonsterMasterDisplayLogic?
  
    // MARK: Do something
    
}
