//
//  SerialModels.swift
//  Teremok-TV
//
//  Created by R9G on 06/09/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Serial {
    // MARK: Use cases
  
    struct Item: Hashable {
      
        var name: String = ""
        var imageUrl: String = ""
        var description: String = ""
        var isLikeMe: Bool = false
        var isDownload: Bool = false
    }
    
    enum Screen {
        case razdel(_ id: Int)
        case search(_ text: String)
        case catalog
    }
}
