//
//  ChoiceAnimalModels.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 25/05/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ChoiceAnimal {
    // MARK: Use cases
  
    enum PrincesState {
        case happy
        case angry

        var image : UIImage? {
            switch self {
            case .happy:
                return UIImage(named: "icPrincesHappy")
            case .angry:
                return UIImage(named: "icPrincesAngry")
            }
        }
    }
    static let fireworks = ["Firework_1", "Firework_2", "Firework_3", "Firework_4"]
    static let sadSounds = ["sad_1", "sad_2", "sad_3"]
    static let funSounds = ["fun_4", "fun_5", "fun_6", "fun_7"]

}
