//
//  AlphaviteStatisticRouter.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 17/08/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlphaviteStatisticRoutingLogic: CommonRoutingLogic {
    
}

protocol AlphaviteStatisticDataPassing {
    var dataStore: AlphaviteStatisticDataStore? { get }
}

class AlphaviteStatisticRouter: AlphaviteStatisticRoutingLogic, AlphaviteStatisticDataPassing {
    weak var viewController: AlphaviteStatisticViewController?
    var dataStore: AlphaviteStatisticDataStore?
    var modalControllersQueue = Queue<UIViewController>()

    // MARK: Routing

//    func routeToSomewhere(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            let destinationVC = segue.destination as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
//      }
//    }

//    // MARK: Navigation
//    func navigateToSomewhere(source: AlphaviteStatisticViewController, destination: SomewhereViewController) {
//        source.show(destination, sender: nil)
//    }
//
//    //MARK: Passing data
//    func passDataToSomewhere(source: AlphaviteStatisticDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
