//
//  AlphaviteStatisticInteractor.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 17/08/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlphaviteStatisticBusinessLogic {
    func fetchStat()
}

protocol AlphaviteStatisticDataStore {
    
}

class AlphaviteStatisticInteractor: AlphaviteStatisticBusinessLogic, AlphaviteStatisticDataStore {
    var presenter: AlphaviteStatisticPresentationLogic?
    let service: AlphabetServiceProtocol = AlphabetService()

    func fetchStat() {
        service.getStat { [weak self] result in
            guard let self = self else { return }

            switch result {
            case .success(let stats):
                self.presenter?.presentStat(response: stats)
            case .failure(let error):
                self.presenter?.presentError(error: error)
            }
        }
    }
}
