//
//  AlphaviteStatisticPresenter.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 17/08/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlphaviteStatisticPresentationLogic: CommonPresentationLogic {
    func presentStat(response: AlphaviteStatisticResponse)
}

class AlphaviteStatisticPresenter: AlphaviteStatisticPresentationLogic {
    weak var viewController: AlphaviteStatisticDisplayLogic?
    var displayModule: CommonDisplayLogic? {
        return viewController
    }

    func presentStat(response: AlphaviteStatisticResponse) {
        let good = Dictionary(uniqueKeysWithValues: response.good.map{ ($0.char, $0.value) })
        let bad = Dictionary(uniqueKeysWithValues: response.bad.map{ ($0.char, $0.value) })
        let model = AlphaviteStatisticViewController.Input(good: good, bad: bad)
        viewController?.showStats(model)
    }
}
