//
//  AchievesPresenter.swift
//  Teremok-TV
//
//  Created by R9G on 27/09/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AchievesPresentationLogic: CommonPresentationLogic {
    func presentAchieves(_ model: [AchievementsResponse])
}

class AchievesPresenter: AchievesPresentationLogic {
    weak var viewController: AchievesDisplayLogic?
    var displayModule: CommonDisplayLogic? {
        return viewController
    }
    // MARK: Do something
    func presentAchieves(_ model: [AchievementsResponse]){
        
        var items: [Achieves.Achievement] = []
        model.forEach { response in
            items.append(Achieves.Achievement(title: response.name ?? "", subtitle: response.description ?? "", imageLink: response.imageLink ?? "", progress: response.progress ?? 0, target: response.target ?? 0))
        }
        viewController?.displayAchieves(items)
    }

}
