//
//  AchievesRouter.swift
//  Teremok-TV
//
//  Created by R9G on 27/09/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AchievesRoutingLogic: CommonRoutingLogic {
    
}

protocol AchievesDataPassing {
    var dataStore: AchievesDataStore? { get }
}

class AchievesRouter: NSObject, AchievesRoutingLogic, AchievesDataPassing {
    weak var viewController: AchievesViewController?
    var dataStore: AchievesDataStore?
    var modalControllersQueue = Queue<UIViewController>()

    // MARK: Routing

}
