//
//  AchievesModels.swift
//  Teremok-TV
//
//  Created by R9G on 27/09/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


enum Achieves {
    struct Achievement {
        let title: String
        let subtitle: String
        let imageLink: String
        let progress: Int
        let target: Int
    }
}
