//
//  ColorsGameStatPresenter.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 12.10.2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ColorsGameStatPresentationLogic: CommonPresentationLogic {
    func presentStat(response: AlphaviteStatisticResponse)

}

class ColorsGameStatPresenter: ColorsGameStatPresentationLogic {
    weak var viewController: ColorsGameStatDisplayLogic?
    var displayModule: CommonDisplayLogic? {
        return viewController
    }
    func presentStat(response: AlphaviteStatisticResponse) {
        let good = Dictionary(uniqueKeysWithValues: response.good.prefix(5).map { (ColorsMaster.Colors(rawValue: $0.char), $0.value) })
        let bad = Dictionary(uniqueKeysWithValues: response.bad.prefix(5).map{ (ColorsMaster.Colors(rawValue: $0.char), $0.value) })
        let model = ColorsGameStatViewController.Input(good: good, bad: bad)
        viewController?.showStats(model)
    }
}
