//
//  AppLaunchScreenRouter.swift
//  Teremok-TV
//
//  Created by R9G on 17/10/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppLaunchScreenRoutingLogic: CommonRoutingLogic {
    
}

protocol AppLaunchScreenDataPassing {
    var dataStore: AppLaunchScreenDataStore? { get }
}

class AppLaunchScreenRouter: NSObject, AppLaunchScreenRoutingLogic, AppLaunchScreenDataPassing {
    weak var viewController: AppLaunchScreenViewController?
    var dataStore: AppLaunchScreenDataStore?
    var modalControllersQueue = Queue<UIViewController>()

    // MARK: Routing

//    func routeToSomewhere(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            let destinationVC = segue.destination as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
//      }
//    }

//    // MARK: Navigation
//    func navigateToSomewhere(source: AppLaunchScreenViewController, destination: SomewhereViewController) {
//        source.show(destination, sender: nil)
//    }
//
//    //MARK: Passing data
//    func passDataToSomewhere(source: AppLaunchScreenDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
