//
//  AppLaunchScreenInteractor.swift
//  Teremok-TV
//
//  Created by R9G on 17/10/2018.
//  Copyright (c) 2018 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppLaunchScreenBusinessLogic {
    
}

protocol AppLaunchScreenDataStore {
    
}

class AppLaunchScreenInteractor: AppLaunchScreenBusinessLogic, AppLaunchScreenDataStore {
    var presenter: AppLaunchScreenPresentationLogic?

    // MARK: Do something

}
