//
//  MusicMasterModels.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 16/03/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MusicMaster {
    // MARK: Use cases
  
    enum ItemType {
        case online(idx: Int, playlist: MusicPlaylistResponse)
        case offline(idx: Int, models: [OfflineMusicModel])
    }

    struct OfflineMusicModel {
        let id: Int
        let name: String
        let albumName: String
        let url: URL
    }
}
