//
//  AnimalsRoundsPresenter.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 19/05/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AnimalsRoundsPresentationLogic: CommonPresentationLogic {
    func presentList(_ list: [AnimalListResponse])

}

class AnimalsRoundsPresenter: AnimalsRoundsPresentationLogic {
    weak var viewController: AnimalsRoundsDisplayLogic?
    var displayModule: CommonDisplayLogic? {
        return viewController
    }
    
    func presentList(_ list: [AnimalListResponse]) {
        let items: [AnimalsRounds.Item] = list.map { AnimalsRounds.Item(name: $0.name ?? "", imageUrl: $0.icon ?? "") }
        viewController?.displayList(items)
    }
}
