//
//  AnimalsStatisticRouter.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 25/05/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AnimalsStatisticRoutingLogic: CommonRoutingLogic {
    
}

protocol AnimalsStatisticDataPassing {
    var dataStore: AnimalsStatisticDataStore? { get }
}

class AnimalsStatisticRouter: AnimalsStatisticRoutingLogic, AnimalsStatisticDataPassing {
    weak var viewController: AnimalsStatisticViewController?
    var dataStore: AnimalsStatisticDataStore?
    var modalControllersQueue = Queue<UIViewController>()

    // MARK: Routing

}
