//
//  PlaylistsPresenter.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 17/03/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlaylistsPresentationLogic: CommonPresentationLogic {
    func present(item: MusicPlaylistResponse)
}

class PlaylistsPresenter: PlaylistsPresentationLogic {
    weak var viewController: PlaylistsDisplayLogic?
  
    var displayModule: CommonDisplayLogic? {
        return viewController
    }

    func present(item: MusicPlaylistResponse) {
        guard let tracks = item.items else { return }

        var playlistTracks: [Playlist.Track] = []
        for track in tracks {
            let itemTrack = Playlist.Track(title: track.name, subtitle: item.name ?? "")
            playlistTracks.append(itemTrack)
        }
        let playlist = Playlist.Item(imageUrl: item.poster ?? "", albumTitle: item.name ?? "", tracks: playlistTracks)
        viewController?.displayPlaylist(playlist)
    }

}
