//
//  OfflinePlaylistPresenter.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 21/04/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OfflinePlaylistPresentationLogic: CommonPresentationLogic {
    func presentLocal(tracks: [URL], completion: (([Int]) -> Void))
}

class OfflinePlaylistPresenter: OfflinePlaylistPresentationLogic {
    weak var viewController: OfflinePlaylistDisplayLogic?
  
    var displayModule: CommonDisplayLogic? {
        return viewController
    }

    func presentLocal(tracks: [URL], completion: (([Int]) -> Void)) {
        var playlist: [MusicMaster.OfflineMusicModel] = []
        for track in tracks {
            let name: [String] = track.deletingPathExtension().lastPathComponent.components(separatedBy: ".")
            let idString = name.first ?? ""
            let item = MusicMaster.OfflineMusicModel(
                id: Int(idString) ?? 0,
                name: name[safe: 1] ?? "",
                albumName: name[safe: 2] ?? "",
                url: track
            )
            playlist.append(item)
        }
        completion(playlist.map { $0.id })
        viewController?.displayPlaylist(playlist)
    }
}
