//
//  OfflinePlaylistRouter.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 21/04/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OfflinePlaylistRoutingLogic {
    func playTrack(track: Int, playlist: [MusicMaster.OfflineMusicModel])
}

protocol OfflinePlaylistDataPassing {
    var dataStore: OfflinePlaylistDataStore? { get }
}

class OfflinePlaylistRouter: NSObject, OfflinePlaylistRoutingLogic, OfflinePlaylistDataPassing, CommonRoutingLogic {
    weak var viewController: OfflinePlaylistViewController?
    var dataStore: OfflinePlaylistDataStore?
    var modalControllersQueue = Queue<UIViewController>()
    var isNew = true

    func playTrack(track: Int, playlist: [MusicMaster.OfflineMusicModel]) {
        guard Profile.current?.premiumMusic ?? false else {
            viewController?.present(errorString: "Для прослушивания необходимо оформить «Дети Супер +»", completion: nil)
            return
        }
        viewController?.master?.play(type: .offline(idx: track, models: playlist), isNew: isNew)
        isNew = false
    }
}
