//
//  SearchMusicRouter.swift
//  Teremok-TV
//
//  Created by Evgeny Ivanov on 14/04/2019.
//  Copyright (c) 2019 xmedia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchMusicRoutingLogic {
    func navigateToAlbum(number: Int)
}

protocol SearchMusicDataPassing {
    var dataStore: SearchMusicDataStore? { get }
}

class SearchMusicRouter: NSObject, SearchMusicRoutingLogic, SearchMusicDataPassing, CommonRoutingLogic {
    weak var viewController: SearchMusicViewController?
    var dataStore: SearchMusicDataStore?
    var modalControllersQueue = Queue<UIViewController>()

    func navigateToAlbum(number: Int) {
        let playlist = PlaylistsViewController.instantiate(fromStoryboard: .music)
        guard var dataStore = playlist.router?.dataStore else { return }
        guard let id = viewController?.router?.dataStore?.albums[safe: number]?.album?.id else {
            return
        }
        dataStore.albumId = id
        viewController?.masterRouter?.presentNextChild(viewController: playlist)
    }
}
